../rtl/core_pkg.sv
../rtl/mem_pkg.sv
../rtl/regfile.sv
../rtl/if1_stage.sv
../rtl/if2_stage.sv
../rtl/id_stage.sv
../rtl/exe_stage.sv
../rtl/mem_stage.sv
../rtl/wb_stage.sv
../rtl/biu.sv
../rtl/mem_bram.sv
../rtl/uart_mmio.sv
../rtl/mem.sv
../rtl/neocorefx_core.sv
../rtl/neocorefx_top.sv
../rtl/neocorefx_fpga_top.sv
