+incdir+../rtl
../rtl/mem_pkg.sv
../rtl/mem_bram.sv
../rtl/uart_mmio.sv
../rtl/debug_mmio.sv
../rtl/debug_uart_agent_pkg.sv
../rtl/debug_uart_agent_memops.sv
../rtl/debug_uart_agent_executor.sv
../rtl/debug_uart_agent_transport.sv
../rtl/debug_uart_agent.sv
../rtl/mem_fabric_slaves.sv
../rtl/mem.sv
